# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sample_acceleration' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'Charts', '~> 3.0'
  use_frameworks!

  # Pods for sample_acceleration

end
